---
title: Kies een achtergrond uit de Scratch bibliotheek
hero_image: images/banner.png
description: Kies een achtergrond uit de Scratch bibliotheek
listed: false
ingredient: true
copyedit: true
steps:
  - title: Kies een achtergrond
