---
title: Voeg een achtergrond toe vanuit de Achtergrondbibliotheek
hero_image: images/banner.png
description: Voeg een achtergrond toe vanuit de Achtergrondbibliotheek
listed: false
ingredient: true
copyedit: true
steps:
  - title: Voeg een achtergrond toe vanuit de Achtergrondbibliotheek
