title: Adding a backdrop from the Scratch library
hero_image: images/banner.png
description: Adding a backdrop from the Scratch library
listed: false
ingredient: true
copyedit: true
steps:
  - title: Adding a backdrop
