---
title: Scratch लाइब्रेरी से पृष्ठभूमि(backdrop) चुनें
hero_image: images/banner.png
description: Scratch लाइब्रेरी से पृष्ठभूमि(backdrop) चुनें
listed: false
ingredient: true
copyedit: true
steps:
  - title: एक पृष्ठभूमि चुनें
