---
title: Scractch লাইব্রেরি থেকে একটি পটভূমি বা backdrop চয়ন করুন
hero_image: images/banner.png
description: Scractch লাইব্রেরি থেকে একটি পটভূমি বা backdrop চয়ন করুন
listed: false
ingredient: true
copyedit: true
steps:
  - title: একটি পটভূমি বা backdrop চয়ন করুন
