---
title: Scratch நூலகத்திலிருந்து பின்னணியைத் தேர்வுசெய்க
hero_image: படங்கள்/banner.png
description: Scratch நூலகத்திலிருந்து பின்னணியைத் தேர்வுசெய்க
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: பின்னணியைத் தேர்வுசெய்க
