---
title: Velg et bakgrunnsbilde fra Scratch-biblioteket
hero_image: images/banner.png
description: Choose a backdrop from the Scratch Library
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Velg et bakgrunnsbilde
