---
title: Velg et bakgrunnsbilde fra Scratch-biblioteket
hero_image: images/banner.png
description: Velg et bakgrunnsbilde fra Scratch-biblioteket
listed: false
ingredient: true
copyedit: true
steps:
  - title: Velg et bakgrunnsbilde
