---
title: Add a backdrop from the Backdrop Library
hero_image: stampi / banner.png
description: Add a backdrop from the Backdrop Library
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Add a backdrop from the Backdrop Library
