---
title: Chọn phông nền từ thư viện Scratch
hero_image: images/banner.png
description: Choose a backdrop from the Scratch Library
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Chọn phông nền
