---
title: Chọn phông nền từ thư viện Scratch
hero_image: images/banner.png
description: Chọn phông nền từ thư viện Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - title: Chọn phông nền
