---
title: Vælg en baggrund fra Scratch-biblioteket
hero_image: images/banner.png
description: Vælg en baggrund fra Scratch-biblioteket
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Vælg en baggrund
