---
title: Escolha um pano de fundo na biblioteca Scratch
hero_image: imagens / banner.png
description: Escolha um pano de fundo na biblioteca Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Choose a backdrop
