---
title: Odaberi pozadinu iz Scratch knjižnice
hero_image: images/banner.png
description: Odaberi pozadinu iz Scratch knjižnice
listed: false
ingredient: true
copyedit: true
steps:
  - title: Odaberi pozadinu
