---
title: Odaberi pozadinu iz Scratch knjižnice
hero_image: images/banner.png
description: Choose a backdrop from the Scratch Library
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Odaberi pozadinu
