---
title: Elige un fondo de la librería de Scratch
hero_image: images/banner.png
description: Elige un fondo de la librería de Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Choose a backdrop
