---
title: Ein Bühnenbild aus der Scratch-Bibliothek auswählen
hero_image: images/banner.png
description: Ein Bühnenbild aus der Scratch-Bibliothek auswählen
listed: false
ingredient: true
copyedit: true
steps:
  - title: Wähle ein Bühnenbild
