---
title: Ein B체hnenbild aus der Scratch-Bibliothek ausw채hlen
hero_image: images/banner.png
description: Choose a backdrop from the Scratch Library
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: W채hle ein B체hnenbild
