---
title: Alege un decor din biblioteca Scratch
hero_image: images/banner.png
description: Alege un decor din biblioteca Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Alege un decor
