---
title: Escolha um plano de fundo na biblioteca Scratch
hero_image: images/banner.png
description: Escolha um plano de fundo na biblioteca Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - title: Escolha um pano de fundo
