---
title: Adicione um plano de fundo da Biblioteca de Cenários
hero_image: images/banner.png
description: Adicione um plano de fundo da Biblioteca de Cenários
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Adicione um plano de fundo da Biblioteca de Cenários
