---
title: Pilih latar dari pustaka Scratch
hero_image: images/banner.png
description: Pilih latar dari pustaka Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Pilih latar
