---
title: Tria un fons de la biblioteca de Scratch
hero_image: images/banner.png
description: Tria un fons de la biblioteca de Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Tria un fons
