---
title: Izberi ozadje iz Scratch knjižnice
hero_image: images / banner.png
description: Izberi ozadje iz Scratch knjižnice
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Izberi ozadje
