---
title: Výběr pozadí z knihovny Scratch
hero_image: images/banner.png
description: Choose a backdrop from the Scratch Library
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Vybrat pozadí
