---
title: Válassz egy hátteret a Scratch könyvtárból
hero_image: images/banner.png
description: Válassz egy hátteret a Scratch könyvtárból
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Válassz egy hátteret
