---
title: Válassz egy hátteret a Scratch könyvtárból
hero_image: images/banner.png
description: Choose a backdrop from the Scratch Library
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Válassz egy hátteret
