---
title: Scratch ಲೈಬ್ರರಿಯಿಂದ ಬ್ಯಾಕ್‌ಡ್ರಾಪ್ ಆಯ್ಕೆಮಾಡಿ
hero_image: images/banner.png
description: Scratch ಲೈಬ್ರರಿಯಿಂದ ಬ್ಯಾಕ್‌ಡ್ರಾಪ್ ಆಯ್ಕೆಮಾಡಿ
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Add a backdrop from the Backdrop Library
