---
title: Agrega un fondo de la biblioteca de Fondos
hero_image: images/banner.png
description: Agrega un fondo de la biblioteca de Fondos
listed: false
ingredient: true
copyedit: true
steps:
  - title: Agrega un fondo de la biblioteca de Fondos
