---
title: Elige un fondo de la librería de Scratch
hero_image: images/banner.png
description: Choose a backdrop from the Scratch Library
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Elige un fondo
