---
title: Wybierz tło z biblioteki Scratch
hero_image: images/banner.png
description: Wybierz tło z biblioteki Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - title: Wybierz tło z biblioteki Scratch
