---
title: ከስክራች ቤተ-መጽሐፍት አንድ የጀርባ ምስል ይምረጡ።
hero_image: images / banner.png
description: Choose a backdrop from the Scratch Library
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: የጀርባ ምስል ይምረጡ
