---
title: Choisir un arrière-plan à partir de la bibliothèque Scratch
hero_image: images/banner.png
description: Choisir un arrière-plan à partir de la bibliothèque Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Choisissez un arrière plan
