---
title: Scegliere uno sfondo dalla libreria di Scratch
hero_image: images/banner.png
description: Scegli uno sfondo dalla libreria di Scratch
listed: false
ingredient: true
copyedit: true
steps:
  - title: Scegli uno sfondo
