---
title: Scratch kütüphanesinden bir dekor seç
hero_image: images/banner.png
description: Scratch kütüphanesinden bir dekor seç
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Bir dekor seç
